spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cnkart
    username: root
    password: Varun@123loyal
  jpa:
    properties.hibernate-dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: create